global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using MediatR;
global using Zapper.LoyaltyPoints.Application.Responses;
global using Zapper.LoyaltyPoints.Application.Interfaces;
global using Zapper.LoyaltyPoints.Domain.Interfaces;
